"""empty message

Revision ID: 9da529aa0333
Revises: f3a1c2b4d5e6
Create Date: 2025-11-25 08:30:01.526936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da529aa0333'
down_revision: Union[str, Sequence[str], None] = 'f3a1c2b4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('utility_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utility_bills_max_power'))
        batch_op.drop_index(batch_op.f('ix_utility_bills_year_month'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utility_bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utility_bills_year_month'), ['year', 'month'], unique=False)
        batch_op.create_index(batch_op.f('ix_utility_bills_max_power'), ['max_power'], unique=False)

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###
