"""drop total_steps from projects

Revision ID: 9f2a309a41bb
Revises: c71cea36552f
Create Date: 2025-11-26 16:21:52.129763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f2a309a41bb'
down_revision: Union[str, Sequence[str], None] = 'c71cea36552f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('total_steps')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_steps', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
