"""empty message

Revision ID: b79f555bde85
Revises: 
Create Date: 2025-11-26 14:41:40.199815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b79f555bde85'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_catalog',
    sa.Column('mc_code', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('revised_date', sa.Date(), nullable=True),
    sa.Column('energy_per_mile', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('mc_code')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('utility', sa.String(length=64), nullable=True),
    sa.Column('utility_account', sa.String(length=64), nullable=True),
    sa.Column('utility_name', sa.String(length=64), nullable=True),
    sa.Column('meter_number', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('contact_name', sa.String(length=128), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('main_breaker_amps', sa.Integer(), nullable=True),
    sa.Column('voltage', sa.Integer(), nullable=True),
    sa.Column('phase_count', sa.Integer(), nullable=True),
    sa.Column('power_factor', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('equipment_identifier', sa.String(length=64), nullable=True),
    sa.Column('mc_code', sa.String(length=16), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('annual_miles', sa.Float(), nullable=True),
    sa.Column('downtime_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mc_code'], ['equipment_catalog.mc_code'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_mc_code'), ['mc_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_site_id'), ['site_id'], unique=False)

    op.create_table('project_sites',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'site_id'),
    sa.UniqueConstraint('project_id', 'site_id', name='uq_project_site')
    )
    op.create_table('project_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('status_date', sa.DateTime(), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'site_id', 'status_date', name='uq_project_site_statusdate')
    )
    with op.batch_alter_table('project_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_status_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_status_site_id'), ['site_id'], unique=False)

    op.create_table('utility_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('energy_usage', sa.Float(), nullable=True),
    sa.Column('max_power', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'year', 'month', name='uq_site_year_month')
    )
    with op.batch_alter_table('utility_bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utility_bills_site_id'), ['site_id'], unique=False)

    op.create_table('equipment_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('miles', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_id', 'year', name='uq_equipment_year')
    )
    with op.batch_alter_table('equipment_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_usage_equipment_id'), ['equipment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_usage_equipment_id'))

    op.drop_table('equipment_usage')
    with op.batch_alter_table('utility_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utility_bills_site_id'))

    op.drop_table('utility_bills')
    with op.batch_alter_table('project_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_status_site_id'))
        batch_op.drop_index(batch_op.f('ix_project_status_project_id'))

    op.drop_table('project_status')
    op.drop_table('project_sites')
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_site_id'))
        batch_op.drop_index(batch_op.f('ix_equipment_mc_code'))

    op.drop_table('equipment')
    op.drop_table('sites')
    op.drop_table('projects')
    op.drop_table('equipment_catalog')
    # ### end Alembic commands ###
