"""add project steps table

Revision ID: c71cea36552f
Revises: b79f555bde85
Create Date: 2025-11-26 16:14:24.140654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71cea36552f'
down_revision: Union[str, Sequence[str], None] = 'b79f555bde85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'step_order', name='uq_project_step_order')
    )
    with op.batch_alter_table('project_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_steps_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_steps_project_id'))

    op.drop_table('project_steps')
    # ### end Alembic commands ###
