"""add chargers table

Revision ID: d951df19f6d2
Revises: 1f3b1b386c0c
Create Date: 2025-12-03 07:51:53.201822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd951df19f6d2'
down_revision: Union[str, Sequence[str], None] = '1f3b1b386c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chargers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('kw', sa.Float(), nullable=True),
    sa.Column('breaker_size', sa.Integer(), nullable=True),
    sa.Column('input_voltage', sa.Integer(), nullable=True),
    sa.Column('output_voltage', sa.Integer(), nullable=True),
    sa.Column('port_count', sa.Integer(), nullable=True),
    sa.Column('handle_type', sa.String(length=32), nullable=True),
    sa.Column('manufacturer', sa.String(length=128), nullable=True),
    sa.Column('model_number', sa.String(length=128), nullable=True),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('date_installed', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chargers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chargers_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chargers_site_id'), ['site_id'], unique=False)
        batch_op.create_index('ix_chargers_site_project', ['site_id', 'project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chargers', schema=None) as batch_op:
        batch_op.drop_index('ix_chargers_site_project')
        batch_op.drop_index(batch_op.f('ix_chargers_site_id'))
        batch_op.drop_index(batch_op.f('ix_chargers_project_id'))

    op.drop_table('chargers')
    # ### end Alembic commands ###
