"""add equipment_categories

Revision ID: daf8c6353813
Revises: cd3795d3ecf1
Create Date: 2025-12-04 13:30:44.432524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daf8c6353813'
down_revision: Union[str, Sequence[str], None] = 'cd3795d3ecf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_catalog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_category_code', sa.String(length=8), nullable=True))
        batch_op.create_index(batch_op.f('ix_equipment_catalog_equipment_category_code'), ['equipment_category_code'], unique=False)
        batch_op.create_foreign_key('equipment_category_code_fkey', 'equipment_categories', ['equipment_category_code'], ['code'])
        batch_op.drop_column('energy_per_mile')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_catalog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('energy_per_mile', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_equipment_catalog_equipment_category_code'))
        batch_op.drop_column('equipment_category_code')

    # ### end Alembic commands ###
