"""Add is_deleted and more site fields.

Revision ID: e22b765a2a1a
Revises: bfa5989e7187
Create Date: 2025-11-21 13:27:27.969976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e22b765a2a1a'
down_revision: Union[str, Sequence[str], None] = 'bfa5989e7187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('utility_account', sa.String(length=64), nullable=True))
    op.add_column('sites', sa.Column('utility_name', sa.String(length=64), nullable=True))
    op.add_column('sites', sa.Column('contact_name', sa.String(length=128), nullable=True))
    op.add_column('sites', sa.Column('contact_phone', sa.String(length=64), nullable=True))
    op.add_column('sites', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'is_deleted')
    op.drop_column('sites', 'contact_phone')
    op.drop_column('sites', 'contact_name')
    op.drop_column('sites', 'utility_name')
    op.drop_column('sites', 'utility_account')
    # ### end Alembic commands ###
